### ISSUE TITLE
Doesn't work on 6000.0.43f1?

### ISSUE THREAD

**Issue by jeong-jimin-github** [danbaidong1111/DanbaidongRP#7]
I'm using the Apple Silicon version of the editor and see the following error

Library/PackageCache/com.unity.render-pipelines.core@17a567797abd/Runtime/GPUDriven/GPUResidentDrawer.cs(790,67): error CS0117: 'GPUDrivenProcessor' does not contain a definition for 'FindUnsupportedMaterialIDs'

**Comment by danbaidong1111** [comment]
Check unity ver -> 6000.0.30f1
Check if all packages imported ("core@17a567797abd" is wrong) -> DanbaidongRPCore DanbaidongRPConfig DanbaidongRP
See documents (I'm sorry it's only in Chinese. u can use chatGPT/DeepSeek to translate) -> https://miusjun13qu.feishu.cn/docx/EXPtdrNmnox8hkx4mnCcy8QNn2b

**Comment by jeong-jimin-github** [comment]
Thank you
